---
postgresql-ha:
  vars:
    ansible_user: hogehoge
    ansible_become: true
    pg_data_dir: /var/lib/pgsql/9.6/data
    pg_log_directory: /var/log/postgresql
    pg_report_directory: /var/www/pg_reports
    pg_port: 5432
    pg_dbname: ingres
    pg_repl_slot_name: repl_slot
    pg_postgres_pwd: your_postgres_pwd
    pg_pgpool_pwd: your_pgpool_pwd
    pg_cron:
      - { name: "get logical backup(pg_dump)", job: "/usr/pgsql-9.6/bin/pgdb_logical_backup.sh {{ pg_dbname }}", hour: 0, minute: 10 }
      - { name: "delete logical backup", job: "/usr/pgsql-9.6/bin/pgdb_logical_backup_delete.sh", hour: 6, minute: 0 }
      - { name: "delete online backup", job: "/usr/pgsql-9.6/bin/pgdb_online_backup_delete.sh", hour: 6, minute: 10 }
      - { name: "delete old log files", job: "/usr/pgsql-9.6/bin/pgdb_log_delete.sh", hour: 6, minute: 20 }
      - { name: "create PostgreSQL Report", job: "/usr/bin/pgbadger -I -q {{ pg_log_directory }}/{{ pg_log_filename }} -O {{ pg_report_directory }}", hour: 6, minute: 30 }
      - { name: "get online backup(pg_basebackup)", job: "/usr/pgsql-9.6/bin/pgdb_online_backup.sh", weekday: 0, hour: 0, minute: 30 }
  children:
    postgresql-primary:
      hosts:
        primary:
      vars:
        ansible_ssh_pass: your_ssh_pwd
        ansible_become_pass: your_become_pwd
        pg_app_user: ingres
        pg_app_user_pwd: your_app_pwd
    postgresql-standby:
      hosts:
        standby:
      vars:
        ansible_ssh_pass: your_ssh_pwd
        ansible_become_pass: your_become_pwd
        pg_cluster_target_host: primary

pgpool2-ha:
  vars:
    ansible_user: hogehoge
    ansible_become: true
    pgp2_backend_hostname0: active
    pgp2_backend_port0: "{{ pg_port }}"
    pgp2_backend_data_directory0: "{{ pg_data_dir }}"
    pgp2_backend_hostname1: standby
    pgp2_backend_port1: "{{ pg_port }}"
    pgp2_backend_data_directory1: "{{ pg_data_dir }}"
    pgp2_delegate_IP: vip
    pgp2_pgpool_pwd: "{{ pg_pgpool_pwd }}"
    pgp2_postgres_pwd: "{{ pg_postgres_pwd }}"
  children:
    pgpool2-active:
      hosts:
        active:
      vars:
        ansible_ssh_pass: your_ssh_pwd
        ansible_become_pass: your_become_pwd
        pgp2_wd_hostname: active
        pgp2_heartbeat_destination0: standby
        pgp2_other_pgpool_hostname0: standby-host
    pgpool2-standby:
      hosts:
        standby:
      vars:
        ansible_ssh_pass: your_ssh_pwd
        ansible_become_pass: your_become_pwd
        pgp2_wd_hostname: standby
        pgp2_heartbeat_destination0: active
        pgp2_other_pgpool_hostname0: active-host
