---
- name: Restart Pgpool-II
  systemd:
    name: pgpool
    state: restarted
    daemon_reload: yes

- name: Restart rsyslog
  systemd:
    name: rsyslog
    state: restarted
    daemon_reload: yes

...
