###################
# {{ pg_data_dir }}/postgresql.conf
###################
# see postgresql-primary/defaults/main.yml

###################
# {{ pg_data_dir }}/pg_hba.conf
###################
# see postgresql-primary/defaults/main.yml

###################
# Common Settings for Custom Operation Script
###################
# see postgresql-primary/defaults/main.yml

###################
# /usr/pgsql-9.6/bin/pgdb_wal_archive_delete.sh
###################
# see postgresql-primary/defaults/main.yml

###################
# /usr/pgsql-9.6/bin/pgdb_logical_backup_delete.sh
###################
# see postgresql-primary/defaults/main.yml

###################
# /usr/pgsql-9.6/bin/pgdb_online_backup_delete.sh
###################
# see postgresql-primary/defaults/main.yml
